import { Geist, Geist_Mono, Libre_Baskerville } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layouts/Navbar";
import Footer from "@/components/layouts/Footer";
import NextAuthProvider from "@/provider/NextAuthProvider";
import { Toaster } from "react-hot-toast";

const libreBaskerville=Libre_Baskerville({
   weight:["400","700"],
   style:['normal','italic']
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <NextAuthProvider>
      <html lang="en">
      <body className={`${libreBaskerville.className} antialiased`}>
        <header className="sticky top-0 z-50">
          <Navbar></Navbar>
        </header>
        <main>
          {children}
        </main>
        <footer>
          <Footer></Footer>
        </footer>
        <Toaster  position="top-center" areverseOrder={false}/>
      </body>
      </html>
    </NextAuthProvider>
  );
}
